from tkinter import *
ans=""
def click(n):
    global ans
    if n=="Clear":
          dt.set("")
          ans=""
    elif n=="back":
             ans=ans[:-1]      
             dt.set(ans)
    elif n=="=":
            re=str(eval(dt.get()))
            ans=re
            dt.set(ans)
    else:
         ans=ans+str(n)
         dt.set(ans)
         print(ans)
root=Tk()
root.title("Calculator")
root.resizable(0,0)
dt=StringVar()
ent=Entry(root,borderwidth=5,font="calibri 32",justify=RIGHT,fg="black",textvariable=dt)
lab=Label(root,text="Calculator",font="calibri 40",fg="black",justify=CENTER)
lab.grid(row=0,column=0,columnspan=4,rowspan=2)
ent.grid(row=2,column=0,columnspan=4,pady=20,padx=10)
b1=Button(root,text="1",font="calbri ",height=2,width=10,command=lambda:click(1))
b2=Button(root,text="2",font="calbri ",height=2,width=10,command=lambda:click(2))
b3=Button(root,text="3",font="calbri ",height=2,width=10,command=lambda:click(3))
b4=Button(root,text="4",font="calbri ",height=2,width=10,command=lambda:click(4))
b5=Button(root,text="5",font="calbri ",height=2,width=10,command=lambda:click(5))
b6=Button(root,text="6",font="calbri ",height=2,width=10,command=lambda:click(6))
b7=Button(root,text="7",font="calbri ",height=2,width=10,command=lambda:click(7))
b8=Button(root,text="8",font="calbri ",height=2,width=10,command=lambda:click(8))
b9=Button(root,text="9",font="calbri ",height=2,width=10,command=lambda:click(9))
b0=Button(root,text="0",font="calbri ",height=2,width=10,command=lambda:click(0))
b_dot=Button(root,text=".",font="calbri ",height=2,width=10,command=lambda:click("."))
b_equal=Button(root,text=" = ",font="calbri ",height=2,width=10,command=lambda:click("="))
b_minus=Button(root,text="-",font="calbri ",height=2,width=10,command=lambda:click("-"))
b_mod=Button(root,text="%",font="calbri ",height=2,width=10,justify=CENTER,command=lambda:click("%"))
b_div=Button(root,text="/",font="calbri ",height=2,width=10,justify=CENTER,command=lambda:click("/"))
b_mult=Button(root,text="*",font="calbri ",height=2,width=10,justify=CENTER,command=lambda:click("*"))
b_add=Button(root,text="+",font="calbri ",height=2,width=10,justify=CENTER,command=lambda:click("+"))
b_back=Button(root,text="Back",font="calbri ",height=2,width=10,justify=RIGHT,command=lambda:click("back"))
b_clear=Button(root,text="Clear",font="calbri ",height=2,width=10,justify=RIGHT,command=lambda:click("Clear"))
b_clear.grid(row=3,column=2,padx=3)
b_back.grid(row=3,column=1)
b1.grid(row=4,column=0)
b2.grid(row=4,column=1)
b3.grid(row=4,column=2)
b_div.grid(row=3,column=3)
b4.grid(row=5,column=0)
b5.grid(row=5,column=1)
b6.grid(row=5,column=2)
b_mod.grid(row=4,column=3)
b_mult.grid(row=5,column=3)
b7.grid(row=6,column=0)
b8.grid(row=6,column=1)
b9.grid(row=6,column=2)
b_add.grid(row=6,column=3)
b0.grid(row=7,column=0)
b_dot.grid(row=7,column=1)
b_minus.grid(row=7,column=2)
b_equal.grid(row=7,column=3)
root.mainloop()